Use utf8mb4 MySQL character set  - Use utf8mb4 as default charset for fresh installation  - utf8mb4 migration command  - warn for collation mix on migration  - Force ROW_FORMAT = Dynamic on fresh install  - Add warning on central page if some tables are not migrated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -224,12 +224,13 @@ jobs:
           docker exec app bin/console glpi:migration:myisam_to_innodb --config-dir=./tests --no-interaction | grep -q "Aucune migration requise." || (echo "glpi:migration:myisam_to_innodb command FAILED" && exit 1)
           docker exec app bin/console glpi:migration:timestamps --config-dir=./tests --no-interaction
           docker exec app bin/console glpi:migration:timestamps --config-dir=./tests --no-interaction | grep -q "Aucune migration requise." || (echo "glpi:migration:timestamps command FAILED" && exit 1)
+          docker exec app bin/console glpi:migration:utf8mb4 --config-dir=./tests --no-interaction
+          docker exec app bin/console glpi:migration:utf8mb4 --config-dir=./tests --no-interaction | grep -q "Aucune migration requise." || (echo "glpi:migration:utf8mb4 command FAILED" && exit 1)
       - name: "Database tests"
         if: env.skip != 'true'
         run: |
-          docker exec app bin/console glpi:database:configure --config-dir=./tests --no-interaction --reconfigure --db-name=glpi --db-host=db --db-user=root
+          docker exec app bin/console glpi:database:configure --config-dir=./tests --no-interaction --reconfigure --db-name=glpi --db-host=db --db-user=root --use-utf8mb4
           docker exec app vendor/bin/atoum -p 'php -d memory_limit=512M' --debug --force-terminal --use-dot-report --bootstrap-file tests/bootstrap.php --no-code-coverage --fail-if-skipped-methods --max-children-number 1 -d tests/database
-          docker exec app bin/console glpi:database:configure --config-dir=./tests --no-interaction --reconfigure --db-name=glpi --db-host=db --db-user=root
       - name: "Unit tests"
         if: env.skip != 'true'
         run: |
