Fail playwright step if errors are found in the logs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -346,12 +346,26 @@ jobs:
       - name: Run Playwright tests
         if: ${{ !cancelled() }}
         run: docker compose exec -T app npx playwright test
+      - name: Check for PHP errors
+        if: ${{ !cancelled() }}
+        run: |
+          if [[ $(wc -l < tests/e2e/glpi_files/_log/php-errors.log) -ge 2 ]]; then
+            echo "PHP errors detected in log file"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
           name: playwright-report
           path: playwright-report/
           retention-days: 30
+      - name: "Upload GLPI logs"
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v5
+        with:
+          name: glpi-playwright-logs
+          path: tests/e2e/glpi_files/_log
+          retention-days: 7
       - name: Publish test summary results
         if: ${{ !cancelled() }}
         run: npx github-actions-ctrf ctrf/ctrf-report.json
