Use temporary file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -349,8 +349,8 @@ jobs:
       - name: Check for PHP errors
         if: ${{ !cancelled() }}
         run: |
-          sed -i '/\*\*\* Test logger/d' tests/e2e/glpi_files/_log/php-errors.log
-          if [[ $(wc -l < tests/e2e/glpi_files/_log/php-errors.log) -ge 2 ]]; then
+          grep -v '\*\*\* Test logger' tests/e2e/glpi_files/_log/php-errors.log > /tmp/php-errors-filtered.log || true
+          if [[ $(wc -l < /tmp/php-errors-filtered.log) -ge 1 ]]; then
             echo "PHP errors detected in log file"
             exit 1
           fi
