Improve db:check command results  - db:check: add success output on clean DB  - glpi-empty.sql: remove extra space  - glpi-empty.sql: lowercase all types  - glpi-empty.sql: add default values for 'timestamp not null' fields  - glpi-empty.sql: add missing default values for tinyint  - glpi-empty.sql: add named constraint on foreign key  - glpi-empty.sql: remove explicit NULL on nullable columns  - validate db:check on installation test suite

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -220,6 +220,8 @@ jobs:
         run: |
           docker exec app bin/console glpi:database:install --config-dir=./tests --ansi --no-interaction --reconfigure --db-name=glpi --db-host=db --db-user=root --log-deprecation-warnings | tee install.log
           if [[ -n $(grep "Warning" install.log) ]]; then echo "glpi:database:install command FAILED" && exit 1; fi
+          docker exec app bin/console glpi:database:check --config-dir=./tests --ansi --no-interaction | tee diff.log
+          if [[ -z $(grep "Database schema is OK." diff.log) ]]; then echo "glpi:database:check command FAILED" && exit 1; fi
           docker exec app bin/console glpi:database:update --config-dir=./tests --ansi --no-interaction | tee migration.log
           if [[ -z $(grep "No migration needed." migration.log) ]]; then echo "glpi:database:update command FAILED" && exit 1; fi
       - name: "Update DB tests (from 0.80, not using utf8mb4)"
